# Site settings
title: Web Opac App
email: info@opacapp.net
description: "Public libraries on android"
baseurl: ""
url: "https://opacapp.net"
siteurl: ""

# Build settings
markdown: kramdown
redcarpet:
    extensions: [footnotes]
permalink: /:path/:basename/

sass:
  style: compressed

navigation_de:
  - title: Startseite
    url: /de/
  - title: Bibliotheken
    url: /de/bibliotheken/
  - title: Features
    url: /de/features/
  - title: App-Editionen
    url: /de/fuer-bibliotheken/
  - title: FAQ
    url: /de/faq/
  - title: Kontakt
    url: /de/kontakt/
  - title: English
    url: /en/

navigation_en:
  - title: Front page
    url: /en/
  - title: Libraries
    url: /en/libraries/
  - title: Features
    url: /en/features/
  - title: App Editions
    url: /en/for-libraries/
  - title: FAQ
    url: /en/faq/
  - title: Contact
    url: /en/contact/
  - title: Deutsch
    url: /de/

uncss:
  stylesheets:
    - css/main.css
  compress: true