# Site settings
title: Web Opac App
email: info@opacapp.net
description: "Public libraries on android"
baseurl: ""
url: "https://opac.app"
siteurl: ""

# Build settings
markdown: kramdown
redcarpet:
    extensions: [footnotes]
permalink: /:path/:basename/

sass:
  style: compressed

navigation_de:
  - title: Startseite
    url: /de/
  - title: Bibliotheken
    url: /de/libraries/
  - title: Features
    url: /de/features/
  - title: App-Editionen
    url: /de/for-libraries/
  - title: FAQ
    url: /de/faq/
  - title: Kontakt
    url: /de/contact/

navigation_en:
  - title: Front page
    url: /en/
  - title: Libraries
    url: /en/libraries/
  - title: Features
    url: /en/features/
  - title: App Editions
    url: /en/for-libraries/
  - title: FAQ
    url: /en/faq/
  - title: Contact
    url: /en/contact/

navigation_fr:
- title: Accueil
  url: /fr/
- title: Bibliothèques
  url: /fr/libraries/
- title: Fonctionnalités
  url: /fr/features/
- title: Pour les bibliothèques
  url: /fr/for-libraries/
- title: FAQ
  url: /fr/faq/
- title: Contact
  url: /fr/contact/

languages:
- title: Deutsch
  code: de
- title: English
  code: en
- title: Français
  code: fr

uncss:
  stylesheets:
    - css/main.css
  compress: true
  ignore:
    - .collection .collection-item
    - .collection a.collection-item
    - .collection a.collection-item:hover

defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "de"
    values:
      lang: "de"
  - scope:
      path: "fr"
    values:
      lang: "fr"